### ISSUE TITLE
esp8266 and esp32 support

### ISSUE THREAD

**Issue by brunnels** [Archer4499/Fan-Tach-Modifier#2]
Do you know if this could be made to work with esp8266?  

I have some of the dell delta 750w platinum power supplies that get used in lots of servers/switches.  The crypto miner people are re-purposing them with breakout boards to power mining rigs.  I've also found people that mod them to boost the voltage to 14v for use as high output LiPO battery charger sources.

You can't put a different fan in the power supplies because it will just try to run it at the RPM set in the programmed fan curve so that's why your solution is needed.

esp8266 support would be great so it can be remotely accessed to view/modify the settings.  The power supply has 3.3v readily available on it's controller board so it would be easy to power the esp8266.  

5v is nowhere to be found but last resort I can still use a pro-mini board via the standby 12v power.

The power supplies have i2c/smbus/pmbus that can be used to pull stats.  I've found python and arduino code to do this.  You can also upload modified fan curves but would need the docs and I haven't found any.

**Comment by brunnels** [comment]
looks like https://github.com/khoih-prog/ESP8266TimerInterrupt?tab=readme-ov-file#usage would be the way to go?

https://github.com/khoih-prog/ESP8266TimerInterrupt/blob/master/examples/ISR_RPM_Measure/ISR_RPM_Measure.ino

**Comment by brunnels** [comment]
I picked up a few esp32-c3 micro boards because they were super cheap.  I threw esphome on them so I could do some easy testing.

Here's what I'm thinking could work.

esphome has a [duty cycle sensor](https://esphome.io/components/sensor/duty_cycle.html).  To test, I hooked this to another esp32 where I generate a 20khz pwm signal.  As I change the duty cycle of the pwm signal, I can see the duty cycle sensor reading go up and down and it's within about 5% of what I'm generating.

So using this sensor and then generating a pwm signal on another pin hooked to a transistor I should be able to simulate the tachometer signal from the duty cycle sensor reading and the max rpm of the simulated fan.

Then on 2 other pins, I can connect the actual fan tach and pwm so I can control it according to the duty cycle sensor.  I would use the tach signal as a sensor on the esphome and for safety to stop sending the fake signal if the fan stops spinning.

**Comment by brunnels** [comment]
@Archer4499 Here's what I came up with.  I've tested and it works with 2 fans no problem.

```yaml
substitutions:
  PS_ON: GPIO21
  FAN_TACH: GPIO4
  FAN_DUTY_MULTIPIER: "0.65"
  FAN_PWM: GPIO3
  FAN_MIN: "0.15"
  FAN_MAX: "1.0"
  OUT_TACH: GPIO1
  OUT_TACH_MAX_RPM: "23000"
  DUTY: GPIO0

esphome:
  name: dell-ps1
  friendly_name: Dell PS1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  logs:
    update_pwm_duty: INFO
    update_out_tach_freq: INFO
    update_out_tach: ERROR

# Throttle writing parameters to the internal flash memory to reduce ESP memory wear / degradation
preferences:
  flash_write_interval: 15min

mdns:
  disabled: true

web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "****"

ota:
  - platform: esphome
    password: "*****"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.35.0.17
  fast_connect: True
  manual_ip:
    static_ip: 10.35.0.17
    gateway: 10.35.0.1
    subnet: 255.255.255.0
    dns1: 10.35.0.1  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dell-Ps1 Fallback Hotspot"
    password: "***"

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"

  - platform: template
    name: "Uptime"
    id: uptime_human
    internal : true

binary_sensor:
  - platform: gpio
    name: "Power On"
    pin:
      number: ${PS_ON}
      mode: input
    on_press:
      - logger.log:
          format: "PS turned ON"
          level: INFO
    on_release:
      - logger.log:
          format: "PS turned OFF"
          level: INFO

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    icon: mdi:clock-start
    update_interval: 1s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();

  - platform: template
    name: "Output Tach RPM"
    unit_of_measurement: "RPM"
    id: out_tach_rpm

  - platform: template
    name: "Fan Speed (PWM Percentage)"
    unit_of_measurement: "%"
    id: fan_speed

  - platform: pulse_counter
    pin: 
      number: ${FAN_TACH}
      mode: INPUT_PULLUP
    unit_of_measurement: "RPM"
    id: fan_speed_tach
    name: "Fan Speed"
    use_pcnt: true
    accuracy_decimals: 0
    filters:
      - multiply: 0.5
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    update_interval: 500ms

  - platform: duty_cycle
    pin: ${DUTY}
    name: "Duty Cycle Sensor"
    id: in_duty_cycle
    update_interval: 500ms
    filters:
      - round: 1
    on_value:
      - script.execute: update_out_tach_freq

output:
  - platform: ledc
    id: fan_speed_pwm
    pin: ${FAN_PWM}
    channel: 0
    frequency: 25000Hz
    min_power: ${FAN_MIN}
    max_power: ${FAN_MAX}

  - platform: ledc
    pin: ${OUT_TACH}
    channel: 4
    id: out_tach
    inverted: True
    min_power: 0.5
    max_power: 0.5

fan:
  - platform: template
    id: manual_fan_control
    entity_category: config
    name: "Manual Fan Speed"
    speed_count: 100
    restore_mode: RESTORE_DEFAULT_OFF 

  - platform: template
    id: manual_tach
    entity_category: config
    name: "Manual Tachometer Speed"
    speed_count: 100
    restore_mode: RESTORE_DEFAULT_OFF

globals:
  - id: out_tach_freq
    type: float
    initial_value: "0.0"

  - id: out_pwm_duty
    type: float
    initial_value: "0.0"
    
script:
  - id: update_pwm_duty
    then:
    - lambda: |-
        float pwm_duty = (id(manual_fan_control).state) ? id(manual_fan_control).speed / 100.0 : id(in_duty_cycle).state / 100.0;        
        if(id(out_pwm_duty) != pwm_duty) {
          ESP_LOGI("update_pwm_duty", "out_pwm_duty changed. was: %.1f now: %.1f", id(out_pwm_duty) * 100.0, pwm_duty * 100.0);
          id(out_pwm_duty) = pwm_duty;
          id(update_fan_speed_pwm).execute();
        }

  - id: update_out_tach_freq
    then:
    - lambda: |-
        id(update_pwm_duty).execute();
        float percentage = (id(manual_tach).state ? id(manual_tach).speed : id(fan_speed).state) / 100.0;
        float freq = (percentage * ${OUT_TACH_MAX_RPM}) / 30.0;
        // drop the decimals
        freq = ((int)freq * 10) / 10.0;       
        if(id(out_tach_freq) != freq) {
          ESP_LOGI("update_out_tach_freq", "out_tach_freq changed. was: %.0f now: %.0f", id(out_tach_freq), freq);
          id(out_tach_freq) = freq;
          id(update_out_tach).execute();          
        }

  - id: update_fan_speed_pwm
    then:
    - lambda: |-
        id(fan_speed_pwm).update_frequency(25000);
        id(fan_speed_pwm).set_level(id(out_pwm_duty) * ${FAN_DUTY_MULTIPIER});
        id(fan_speed).publish_state(id(out_pwm_duty) * 100.0);

  - id: update_out_tach
    then:
    - lambda: |-
        // if the fan tach stops always stop sending out_tach
        if(id(out_tach_freq) < 1.0 || id(fan_speed_tach).state * 1.0 < 5.0) {
          ESP_LOGE("update_out_tach", "out_tach_freq %.0f or fan_speed_tach %.1f invalid! stopping out_tach!", out_tach_freq, id(fan_speed_tach).state * 1.0);
          id(out_tach).turn_off();
          id(out_tach_rpm).publish_state(0);
        } else {
          id(out_tach).turn_on();
          id(out_tach).update_frequency(id(out_tach_freq));
          id(out_tach_rpm).publish_state(id(out_tach_freq) * 30);
        }
```
